name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master  # or main, whatever your default branch is

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # If you have no build step, skip the Node setup and build steps

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./  # change if your static files are in another folder

